# Header

menu:
  主页: /
  相册: /photos

# SubNav
subnav:
  github: "https://github.com/yellowlemon"
  #weibo: "#"
  rss: "/atom.xml"
  #zhihu: "#"
  jianshu: "http://www.jianshu.com/users/6bdf1989b10b/timeline"
  segmentfault: "https://segmentfault.com/u/yellowlemon"
  #douban: "#"
  mail: "mailto:yellowlemon@vip.qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否开启动画效果
animate: true
# 是否在新窗口打开链接
open_in_new: true

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: 
# 微信二维码图片地址
weixin: 

# Miscellaneous
baidu_analytics: '0254b4b9fdc345c1454980c0b64fc3e9'
google_analytics: ''
favicon: /assets/img/favicon.ico

#你的头像url
avatar: /assets/img/avatar.jpg

#是否开启分享
share_jia: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: yellowlemon

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  #friends: '友链'
  aboutme: '关于我'

friends: false

aboutme: <br><br>努力做一个不拖延的程序猿<br>Fighting！